### ISSUE TITLE
Command Dispatch Error

### ISSUE THREAD

**Issue by Sandarr95** [Sandarr95/TGConsole#1]
Duplicate of: https://github.com/Azim-D3Tm/TGConsole/issues/1

```
[18:58:07] [Server thread/INFO]: Done (46.761s)! For help, type "help"
[18:58:15] [GompcraftBot Telegram Executor/INFO]: got update;
[18:58:15] [GompcraftBot Telegram Executor/INFO]: it have text;
[18:58:15] [GompcraftBot Telegram Executor/INFO]: is admin
[18:58:15] [GompcraftBot Telegram Executor/INFO]: User: Sander Kolman @SanderK
[18:58:15] [GompcraftBot Telegram Executor/INFO]: Action: say Something
[18:58:15] [GompcraftBot Telegram Executor/ERROR]: BOTSESSION
java.lang.IllegalStateException: Asynchronous command dispatch!
	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-2012f1e]
	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.dispatchCommand(CraftServer.java:708) ~[spigot-1.14.4.jar:git-Spigot-798ea6a-2012f1e]
	at ru.stormcraft.tgconsole.util.ConsoleUtils.executeCommand(ConsoleUtils.java:20) ~[TGConsole-1.12.jar:?]
	at ru.stormcraft.tgconsole.TGself.onUpdateReceived(TGself.java:141) ~[TGConsole-1.12.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1540) ~[?:?]
	at org.telegram.telegrambots.generics.LongPollingBot.onUpdatesReceived(LongPollingBot.java:27) ~[TelegramBotsAPI.jar:?]
	at org.telegram.telegrambots.updatesreceivers.DefaultBotSession$HandlerThread.run(DefaultBotSession.java:306) [TelegramBotsAPI.jar:?]
```

Possible solution: https://www.spigotmc.org/threads/java-lang-illegalstateexception-asynchronous-command-dispatch.345397/

**Comment by Sandarr95** [comment]
fixed by commit: [a658d2](https://github.com/Sandarr95/TGConsole/commit/a658d2f30d91654fd47d052e9c17ba503c8abda2)
